#!/usr/bin/env bash

set -euo pipefail

mikebd_bash_scripts_test_add_dir=""
mikebd_bash_scripts_test_config=""
mikebd_bash_scripts_test_fake=""
mikebd_bash_scripts_test_fake_output=""
mikebd_bash_scripts_test_fake_bin=""
mikebd_bash_scripts_test_primary=""
mikebd_bash_scripts_test_root=""
mikebd_bash_scripts_test_target=""
mikebd_bash_scripts_test_tmp_root=""
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
# shellcheck source=test-lib.sh disable=SC1091
source "$script_dir/test-lib.sh"
trap 'mikebd_bash_scripts_test_cleanup' EXIT

mikebd_bash_scripts_test_setup_fixture
mikebd_bash_scripts_test_setup_fake_codex
marker='# Generated by generic launcher test; do not edit by hand.'
invalid_launcher="$mikebd_bash_scripts_test_tmp_root/codex-invalid-marker"
if mikebd_launcher_render "$invalid_launcher" "$mikebd_bash_scripts_test_target" "" scripts/dx/codex 'not a shell comment'; then
  mikebd_bash_scripts_test_fail "launcher rendering accepted a non-comment marker"
fi
[ ! -e "$invalid_launcher" ] || mikebd_bash_scripts_test_fail "launcher rendering created a launcher for a non-comment marker"
if mikebd_launcher_render "$invalid_launcher" "$mikebd_bash_scripts_test_target" "" scripts/dx/codex $'# valid marker\ninvalid'; then
  mikebd_bash_scripts_test_fail "launcher rendering accepted a multiline marker"
fi
[ ! -e "$invalid_launcher" ] || mikebd_bash_scripts_test_fail "launcher rendering created a launcher for a multiline marker"
invalid_marker_target="$mikebd_bash_scripts_test_tmp_root/invalid-marker-worktree"
if (cd "$mikebd_bash_scripts_test_primary" && "$mikebd_bash_scripts_test_root/codex/launcher/new-worktree-launcher.sh" \
  --worktree-dir "$invalid_marker_target" \
  --branch feature/invalid-marker \
  --launcher "$mikebd_bash_scripts_test_tmp_root/codex-invalid-marker-command" \
  --generator-marker 'not a shell comment' \
  --runner-relative-path scripts/dx/codex) >"$mikebd_bash_scripts_test_tmp_root/invalid-marker-output" 2>&1; then
  mikebd_bash_scripts_test_fail "new-worktree launcher accepted a non-comment marker"
fi
[ ! -e "$invalid_marker_target" ] || mikebd_bash_scripts_test_fail "invalid marker created a worktree"
if git -C "$mikebd_bash_scripts_test_primary" show-ref --verify --quiet refs/heads/feature/invalid-marker; then
  mikebd_bash_scripts_test_fail "invalid marker created a branch"
fi
prepare="$mikebd_bash_scripts_test_tmp_root/prepare"
prepare_output="$mikebd_bash_scripts_test_tmp_root/prepare-output"
cat >"$prepare" <<'EOF'
#!/usr/bin/env bash
printf '%s\n' "$2" >"$PREPARE_OUTPUT"
EOF
chmod 755 "$prepare"

env -u GOCACHE -u GOMODCACHE -u GOTMPDIR -u GOLANGCI_LINT_CACHE -u TMPDIR \
  CODEX_BIN="$mikebd_bash_scripts_test_fake" MIKEBD_BASH_SCRIPTS_TEST_FAKE_OUTPUT="$mikebd_bash_scripts_test_fake_output" PREPARE_OUTPUT="$prepare_output" \
  CODEX_HOME="$mikebd_bash_scripts_test_tmp_root/codex-home" CODEX_LAUNCHER_CONFIG="$mikebd_bash_scripts_test_config" \
  PATH="$mikebd_bash_scripts_test_fake_bin:$PATH" USE_RTK=1 XDG_CACHE_HOME="$mikebd_bash_scripts_test_tmp_root/xdg-cache" \
  "$mikebd_bash_scripts_test_root/codex/launcher/run.sh" --prepare "$prepare" --worktree-dir "$mikebd_bash_scripts_test_target" -- hello
mikebd_bash_scripts_test_assert_file_contains "$prepare_output" "$mikebd_bash_scripts_test_target"
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_fake_output" "ARGS: <--sandbox> <workspace-write> <--model> <test-model>"
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_fake_output" "model_reasoning_effort=low"
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_fake_output" "<$mikebd_bash_scripts_test_add_dir>"
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_fake_output" "<hello>"
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_fake_output" "CODEX_HOME=$mikebd_bash_scripts_test_tmp_root/codex-home"
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_fake_output" "<$mikebd_bash_scripts_test_tmp_root/go-build-cache>"
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_fake_output" "<$mikebd_bash_scripts_test_tmp_root/go-module-cache>"
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_fake_output" "<$mikebd_bash_scripts_test_tmp_root/xdg-cache/golangci-lint>"
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_fake_output" "GOCACHE=<default>"
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_fake_output" "GOMODCACHE=<default>"
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_fake_output" "GOTMPDIR=<default>"
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_fake_output" "GOLANGCI_LINT_CACHE=<default>"
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_fake_output" "TMPDIR=<default>"
[ -d "$mikebd_bash_scripts_test_tmp_root/go-build-cache" ] || mikebd_bash_scripts_test_fail "launcher did not create the Go build cache directory"
[ -d "$mikebd_bash_scripts_test_tmp_root/go-module-cache" ] || mikebd_bash_scripts_test_fail "launcher did not create the Go module cache directory"
[ -d "$mikebd_bash_scripts_test_tmp_root/xdg-cache/golangci-lint" ] || mikebd_bash_scripts_test_fail "launcher did not create the golangci-lint cache directory"

empty_config="$mikebd_bash_scripts_test_tmp_root/empty-launcher.env"
empty_output="$mikebd_bash_scripts_test_tmp_root/empty-array-output"
printf '%s\n' 'CODEX_LAUNCHER_ADD_DIRS=()' >"$empty_config"
env -u CODEX_HOME -u GOCACHE -u GOMODCACHE -u GOTMPDIR -u GOLANGCI_LINT_CACHE -u TMPDIR \
  CODEX_BIN="$mikebd_bash_scripts_test_fake" MIKEBD_BASH_SCRIPTS_TEST_FAKE_OUTPUT="$empty_output" \
  CODEX_LAUNCHER_CONFIG="$empty_config" PATH="$mikebd_bash_scripts_test_fake_bin:$PATH" \
  "$mikebd_bash_scripts_test_root/codex/launcher/run.sh" --worktree-dir "$mikebd_bash_scripts_test_target"
mikebd_bash_scripts_test_assert_file_contains "$empty_output" 'ARGS: <--sandbox> <workspace-write>'
if grep -Fq "<$mikebd_bash_scripts_test_add_dir>" "$empty_output"; then
  mikebd_bash_scripts_test_fail "empty configured directories were passed to Codex"
fi

no_go_bin="$mikebd_bash_scripts_test_tmp_root/no-go-bin"
mkdir -p "$no_go_bin"
env -u GOCACHE -u GOMODCACHE -u GOTMPDIR -u GOLANGCI_LINT_CACHE -u TMPDIR \
  CODEX_BIN="$mikebd_bash_scripts_test_fake" MIKEBD_BASH_SCRIPTS_TEST_FAKE_OUTPUT="$mikebd_bash_scripts_test_fake_output" \
  CODEX_LAUNCHER_CONFIG="$mikebd_bash_scripts_test_config" PATH="$no_go_bin:/usr/bin:/bin" \
  "$mikebd_bash_scripts_test_root/codex/launcher/run.sh" --worktree-dir "$mikebd_bash_scripts_test_target"
if grep -Fq "go-build-cache" "$mikebd_bash_scripts_test_fake_output"; then
  mikebd_bash_scripts_test_fail "non-Go launcher invocation added the Go build cache"
fi
if grep -Fq "go-module-cache" "$mikebd_bash_scripts_test_fake_output"; then
  mikebd_bash_scripts_test_fail "non-Go launcher invocation added the Go module cache"
fi
if grep -Fq "golangci-lint" "$mikebd_bash_scripts_test_fake_output"; then
  mikebd_bash_scripts_test_fail "non-Go launcher invocation added the golangci-lint cache"
fi

generated_target="$mikebd_bash_scripts_test_tmp_root/generated worktree"
launcher="$mikebd_bash_scripts_test_tmp_root/codex-generated"
(cd "$mikebd_bash_scripts_test_primary" && "$mikebd_bash_scripts_test_root/codex/launcher/new-worktree-launcher.sh" \
  --worktree-dir "$generated_target" \
  --branch feature/generated \
  --from HEAD \
  --launcher "$launcher" \
  --generator-marker "$marker" \
  --runner-relative-path scripts/dx/codex) >"$mikebd_bash_scripts_test_tmp_root/new-output"
mikebd_bash_scripts_test_assert_file_contains "$launcher" "# codex-launcher-runner_relative_path-hex:"
mikebd_bash_scripts_test_assert_file_contains "$launcher" "default_session_id=''"
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_tmp_root/new-output" "session.sh pin"

CODEX_BIN="$mikebd_bash_scripts_test_fake" MIKEBD_BASH_SCRIPTS_TEST_FAKE_OUTPUT="$mikebd_bash_scripts_test_fake_output" CODEX_HOME="$mikebd_bash_scripts_test_tmp_root/generated-codex-home" \
  CODEX_LAUNCHER_CONFIG="$mikebd_bash_scripts_test_config" "$launcher" -- generated
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_fake_output" "<generated>"

"$mikebd_bash_scripts_test_root/codex/launcher/session.sh" --generator-marker "$marker" --runner-relative-path scripts/dx/codex \
  pin --launcher "$launcher" --session-id session-123
mikebd_bash_scripts_test_assert_file_contains "$launcher" "default_session_id=session-123"

fork_launcher="$mikebd_bash_scripts_test_tmp_root/codex-fork"
CODEX_BIN="$mikebd_bash_scripts_test_fake" MIKEBD_BASH_SCRIPTS_TEST_FAKE_OUTPUT="$mikebd_bash_scripts_test_fake_output" CODEX_HOME="$mikebd_bash_scripts_test_tmp_root/generated-codex-home" \
  CODEX_LAUNCHER_CONFIG="$mikebd_bash_scripts_test_config" "$mikebd_bash_scripts_test_root/codex/launcher/session.sh" \
  --generator-marker "$marker" --runner-relative-path scripts/dx/codex \
  fork --launcher "$launcher" --target-launcher "$fork_launcher"
mikebd_bash_scripts_test_assert_file_contains "$fork_launcher" "default_session_id=child-123"

legacy_launcher="$mikebd_bash_scripts_test_tmp_root/codex-legacy"
rm -rf "$mikebd_bash_scripts_test_tmp_root/generated-codex-home/sessions"
cat >"$legacy_launcher" <<EOF
#!/usr/bin/env bash
set -euo pipefail
$marker
worktree_dir=$mikebd_bash_scripts_test_target
default_session_id=session-123
EOF
chmod 700 "$legacy_launcher"
legacy_fork_launcher="$mikebd_bash_scripts_test_tmp_root/codex-legacy-fork"
CODEX_BIN="$mikebd_bash_scripts_test_fake" MIKEBD_BASH_SCRIPTS_TEST_FAKE_OUTPUT="$mikebd_bash_scripts_test_fake_output" CODEX_HOME="$mikebd_bash_scripts_test_tmp_root/generated-codex-home" \
  CODEX_LAUNCHER_CONFIG="$mikebd_bash_scripts_test_config" "$mikebd_bash_scripts_test_root/codex/launcher/session.sh" \
  --generator-marker "$marker" --runner-relative-path scripts/dx/codex \
  fork --launcher "$legacy_launcher" --target-launcher "$legacy_fork_launcher"
mikebd_bash_scripts_test_assert_file_contains "$legacy_fork_launcher" "default_session_id=child-123"

failing_prepare="$mikebd_bash_scripts_test_tmp_root/failing-prepare"
cat >"$failing_prepare" <<'EOF'
#!/usr/bin/env bash
exit 23
EOF
chmod 755 "$failing_prepare"
failed_target="$mikebd_bash_scripts_test_tmp_root/failed-prepare-worktree"
if (cd "$mikebd_bash_scripts_test_primary" && "$mikebd_bash_scripts_test_root/codex/launcher/new-worktree-launcher.sh" \
  --worktree-dir "$failed_target" \
  --branch feature/prepare-failure \
  --launcher "$mikebd_bash_scripts_test_tmp_root/codex-failed-prepare" \
  --prepare "$failing_prepare" \
  --generator-marker "$marker" \
  --runner-relative-path scripts/dx/codex) >"$mikebd_bash_scripts_test_tmp_root/failed-prepare-output" 2>&1; then
  mikebd_bash_scripts_test_fail "new-worktree launcher succeeded after preparation failed"
fi
[ ! -e "$failed_target" ] || mikebd_bash_scripts_test_fail "failed preparation left a worktree behind"
if git -C "$mikebd_bash_scripts_test_primary" show-ref --verify --quiet refs/heads/feature/prepare-failure; then
  mikebd_bash_scripts_test_fail "failed preparation left a branch behind"
fi

render_failure_launcher="$mikebd_bash_scripts_test_tmp_root/codex-render-failure"
render_failure_prepare="$mikebd_bash_scripts_test_tmp_root/render-failure-prepare"
cat >"$render_failure_prepare" <<'EOF'
#!/usr/bin/env bash
touch "$PREPARE_FAILURE_LAUNCHER"
EOF
chmod 755 "$render_failure_prepare"
render_failure_target="$mikebd_bash_scripts_test_tmp_root/failed-render-worktree"
if (cd "$mikebd_bash_scripts_test_primary" && PREPARE_FAILURE_LAUNCHER="$render_failure_launcher" "$mikebd_bash_scripts_test_root/codex/launcher/new-worktree-launcher.sh" \
  --worktree-dir "$render_failure_target" \
  --branch feature/render-failure \
  --launcher "$render_failure_launcher" \
  --prepare "$render_failure_prepare" \
  --generator-marker "$marker" \
  --runner-relative-path scripts/dx/codex) >"$mikebd_bash_scripts_test_tmp_root/failed-render-output" 2>&1; then
  mikebd_bash_scripts_test_fail "new-worktree launcher succeeded after rendering failed"
fi
[ ! -e "$render_failure_target" ] || mikebd_bash_scripts_test_fail "failed rendering left a worktree behind"
if git -C "$mikebd_bash_scripts_test_primary" show-ref --verify --quiet refs/heads/feature/render-failure; then
  mikebd_bash_scripts_test_fail "failed rendering left a branch behind"
fi
[ -e "$render_failure_launcher" ] || mikebd_bash_scripts_test_fail "rollback removed the externally created launcher"

echo "PASS: generic launcher tests"
