#!/usr/bin/env bash

set -euo pipefail

mikebd_bash_scripts_test_tmp_root=""
test_script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"

mikebd_bash_scripts_source_isolation_assert() {
  local name="$1"
  local actual="$2"
  local expected="$3"

  [ "$actual" = "$expected" ] || {
    echo "FAIL: $name changed from $expected to $actual" >&2
    exit 1
  }
}

(
  script_dir="caller-script-dir"
  scripts_root="caller-scripts-root"
  repo_root="caller-repo-root"
  tmp_root="caller-tmp-root"
  trap ':' EXIT
  expected_exit_trap="$(trap -p EXIT)"
  expected_shell_options="$(set -o)"
  # shellcheck source=test-lib.sh disable=SC1091
  source "$test_script_dir/test-lib.sh"
  mikebd_bash_scripts_source_isolation_assert script_dir "$script_dir" caller-script-dir
  mikebd_bash_scripts_source_isolation_assert scripts_root "$scripts_root" caller-scripts-root
  mikebd_bash_scripts_source_isolation_assert repo_root "$repo_root" caller-repo-root
  mikebd_bash_scripts_source_isolation_assert tmp_root "$tmp_root" caller-tmp-root
  mikebd_bash_scripts_source_isolation_assert exit_trap "$(trap -p EXIT)" "$expected_exit_trap"
  mikebd_bash_scripts_source_isolation_assert shell_options "$(set -o)" "$expected_shell_options"

  trap ':' RETURN
  expected_return_trap="$(trap -p RETURN)"
  launcher="$mikebd_bash_scripts_test_tmp_root/source-isolation-launcher"
  marker='# Generated by source-isolation test; do not edit by hand.'
  mikebd_launcher_render "$launcher" /tmp/source-isolation-worktree "" scripts/dx/codex "$marker"
  mikebd_bash_scripts_source_isolation_assert return_trap "$(trap -p RETURN)" "$expected_return_trap"
  mikebd_launcher_update_session "$launcher" session-123 "$marker"
  mikebd_bash_scripts_source_isolation_assert return_trap "$(trap -p RETURN)" "$expected_return_trap"
  mikebd_bash_scripts_test_cleanup
)

echo "PASS: source-isolation tests"
