#!/usr/bin/env bash

set -euo pipefail

mikebd_bash_scripts_test_add_dir=""
mikebd_bash_scripts_test_config=""
mikebd_bash_scripts_test_fake=""
mikebd_bash_scripts_test_fake_output=""
mikebd_bash_scripts_test_fake_bin=""
mikebd_bash_scripts_test_primary=""
mikebd_bash_scripts_test_root=""
mikebd_bash_scripts_test_target=""
mikebd_bash_scripts_test_tmp_root=""
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
# shellcheck source=test-lib.sh disable=SC1091
source "$script_dir/test-lib.sh"
trap 'mikebd_bash_scripts_test_cleanup' EXIT

mikebd_bash_scripts_test_setup_fixture
mikebd_bash_scripts_test_setup_fake_codex
marker='# Generated by generic launcher test; do not edit by hand.'
invalid_launcher="$mikebd_bash_scripts_test_tmp_root/codex-invalid-marker"
if mikebd_launcher_render "$invalid_launcher" "$mikebd_bash_scripts_test_target" "" scripts/dx/codex 'not a shell comment'; then
  mikebd_bash_scripts_test_fail "launcher rendering accepted a non-comment marker"
fi
[ ! -e "$invalid_launcher" ] || mikebd_bash_scripts_test_fail "launcher rendering created a launcher for a non-comment marker"
if mikebd_launcher_render "$invalid_launcher" "$mikebd_bash_scripts_test_target" "" scripts/dx/codex $'# valid marker\ninvalid'; then
  mikebd_bash_scripts_test_fail "launcher rendering accepted a multiline marker"
fi
[ ! -e "$invalid_launcher" ] || mikebd_bash_scripts_test_fail "launcher rendering created a launcher for a multiline marker"
invalid_marker_target="$mikebd_bash_scripts_test_tmp_root/invalid-marker-worktree"
if (cd "$mikebd_bash_scripts_test_primary" && "$mikebd_bash_scripts_test_root/codex/launcher/new-worktree-launcher.sh" \
  --worktree-dir "$invalid_marker_target" \
  --branch feature/invalid-marker \
  --launcher "$mikebd_bash_scripts_test_tmp_root/codex-invalid-marker-command" \
  --generator-marker 'not a shell comment' \
  --runner-relative-path scripts/dx/codex) >"$mikebd_bash_scripts_test_tmp_root/invalid-marker-output" 2>&1; then
  mikebd_bash_scripts_test_fail "new-worktree launcher accepted a non-comment marker"
fi
[ ! -e "$invalid_marker_target" ] || mikebd_bash_scripts_test_fail "invalid marker created a worktree"
if git -C "$mikebd_bash_scripts_test_primary" show-ref --verify --quiet refs/heads/feature/invalid-marker; then
  mikebd_bash_scripts_test_fail "invalid marker created a branch"
fi
prepare="$mikebd_bash_scripts_test_tmp_root/prepare"
prepare_output="$mikebd_bash_scripts_test_tmp_root/prepare-output"
cat >"$prepare" <<'EOF'
#!/usr/bin/env bash
printf '%s\n' "$2" >"$PREPARE_OUTPUT"
EOF
chmod 755 "$prepare"

env -u GOCACHE -u GOMODCACHE -u GOTMPDIR -u GOLANGCI_LINT_CACHE -u TMPDIR \
  CODEX_BIN="$mikebd_bash_scripts_test_fake" MIKEBD_BASH_SCRIPTS_TEST_FAKE_OUTPUT="$mikebd_bash_scripts_test_fake_output" PREPARE_OUTPUT="$prepare_output" \
  CODEX_HOME="$mikebd_bash_scripts_test_tmp_root/codex-home" CODEX_LAUNCHER_CONFIG="$mikebd_bash_scripts_test_config" \
  PATH="$mikebd_bash_scripts_test_fake_bin:$PATH" USE_RTK=1 XDG_CACHE_HOME="$mikebd_bash_scripts_test_tmp_root/xdg-cache" \
  "$mikebd_bash_scripts_test_root/codex/launcher/run.sh" --prepare "$prepare" --worktree-dir "$mikebd_bash_scripts_test_target" -- hello
mikebd_bash_scripts_test_assert_file_contains "$prepare_output" "$mikebd_bash_scripts_test_target"
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_fake_output" "ARGS: <--sandbox> <workspace-write> <--model> <test-model>"
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_fake_output" "model_reasoning_effort=low"
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_fake_output" "<$mikebd_bash_scripts_test_add_dir>"
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_fake_output" "<hello>"
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_fake_output" "CODEX_HOME=$mikebd_bash_scripts_test_tmp_root/codex-home"
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_fake_output" "<$mikebd_bash_scripts_test_tmp_root/go-build-cache>"
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_fake_output" "<$mikebd_bash_scripts_test_tmp_root/go-module-cache>"
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_fake_output" "<$mikebd_bash_scripts_test_tmp_root/xdg-cache/golangci-lint>"
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_fake_output" "GOCACHE=<default>"
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_fake_output" "GOMODCACHE=<default>"
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_fake_output" "GOTMPDIR=<default>"
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_fake_output" "GOLANGCI_LINT_CACHE=<default>"
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_fake_output" "TMPDIR=<default>"
[ -d "$mikebd_bash_scripts_test_tmp_root/go-build-cache" ] || mikebd_bash_scripts_test_fail "launcher did not create the Go build cache directory"
[ -d "$mikebd_bash_scripts_test_tmp_root/go-module-cache" ] || mikebd_bash_scripts_test_fail "launcher did not create the Go module cache directory"
[ -d "$mikebd_bash_scripts_test_tmp_root/xdg-cache/golangci-lint" ] || mikebd_bash_scripts_test_fail "launcher did not create the golangci-lint cache directory"

empty_config="$mikebd_bash_scripts_test_tmp_root/empty-launcher.env"
empty_output="$mikebd_bash_scripts_test_tmp_root/empty-array-output"
printf '%s\n' 'CODEX_LAUNCHER_ADD_DIRS=()' >"$empty_config"
env -u CODEX_HOME -u GOCACHE -u GOMODCACHE -u GOTMPDIR -u GOLANGCI_LINT_CACHE -u TMPDIR \
  CODEX_BIN="$mikebd_bash_scripts_test_fake" MIKEBD_BASH_SCRIPTS_TEST_FAKE_OUTPUT="$empty_output" \
  CODEX_LAUNCHER_CONFIG="$empty_config" PATH="$mikebd_bash_scripts_test_fake_bin:$PATH" \
  "$mikebd_bash_scripts_test_root/codex/launcher/run.sh" --worktree-dir "$mikebd_bash_scripts_test_target"
mikebd_bash_scripts_test_assert_file_contains "$empty_output" 'ARGS: <--sandbox> <workspace-write>'
if grep -Fq "<$mikebd_bash_scripts_test_add_dir>" "$empty_output"; then
  mikebd_bash_scripts_test_fail "empty configured directories were passed to Codex"
fi

no_go_bin="$mikebd_bash_scripts_test_tmp_root/no-go-bin"
mkdir -p "$no_go_bin"
link_no_go_command() {
  local command_name="$1"
  local command_path

  command_path="$(command -v "$command_name")" || {
    mikebd_bash_scripts_test_fail "required test command is unavailable: $command_name"
  }
  ln -s "$command_path" "$no_go_bin/$command_name"
}
for no_go_command in bash env git mkdir dirname pwd sed awk grep mktemp chmod mv find; do
  link_no_go_command "$no_go_command"
done
env -u GOCACHE -u GOMODCACHE -u GOTMPDIR -u GOLANGCI_LINT_CACHE -u TMPDIR \
  CODEX_BIN="$mikebd_bash_scripts_test_fake" MIKEBD_BASH_SCRIPTS_TEST_FAKE_OUTPUT="$mikebd_bash_scripts_test_fake_output" \
  CODEX_LAUNCHER_CONFIG="$mikebd_bash_scripts_test_config" PATH="$no_go_bin" \
  "$mikebd_bash_scripts_test_root/codex/launcher/run.sh" --worktree-dir "$mikebd_bash_scripts_test_target"
if grep -Fq "go-build-cache" "$mikebd_bash_scripts_test_fake_output"; then
  mikebd_bash_scripts_test_fail "non-Go launcher invocation added the Go build cache"
fi
if grep -Fq "go-module-cache" "$mikebd_bash_scripts_test_fake_output"; then
  mikebd_bash_scripts_test_fail "non-Go launcher invocation added the Go module cache"
fi
if grep -Fq "golangci-lint" "$mikebd_bash_scripts_test_fake_output"; then
  mikebd_bash_scripts_test_fail "non-Go launcher invocation added the golangci-lint cache"
fi

generated_target="$mikebd_bash_scripts_test_tmp_root/generated worktree"
launcher="$mikebd_bash_scripts_test_tmp_root/codex-generated"
(cd "$mikebd_bash_scripts_test_primary" && "$mikebd_bash_scripts_test_root/codex/launcher/new-worktree-launcher.sh" \
  --worktree-dir "$generated_target" \
  --branch feature/generated \
  --from HEAD \
  --launcher "$launcher" \
  --generator-marker "$marker" \
  --runner-relative-path scripts/dx/codex) >"$mikebd_bash_scripts_test_tmp_root/new-output"
mikebd_bash_scripts_test_assert_file_contains "$launcher" "# codex-launcher-runner_relative_path-hex:"
mikebd_bash_scripts_test_assert_file_contains "$launcher" "default_session_id=''"
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_tmp_root/new-output" "session.sh pin"

CODEX_BIN="$mikebd_bash_scripts_test_fake" MIKEBD_BASH_SCRIPTS_TEST_FAKE_OUTPUT="$mikebd_bash_scripts_test_fake_output" CODEX_HOME="$mikebd_bash_scripts_test_tmp_root/generated-codex-home" \
  CODEX_LAUNCHER_CONFIG="$mikebd_bash_scripts_test_config" "$launcher" -- generated
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_fake_output" "<generated>"

extra_add_dir_one="$mikebd_bash_scripts_test_tmp_root/extra add-dir-one"
extra_add_dir_two="$mikebd_bash_scripts_test_tmp_root/extra-add-dir-two"
mkdir -p "$extra_add_dir_one" "$extra_add_dir_two"
extra_launcher="$mikebd_bash_scripts_test_tmp_root/codex-extra"
extra_target="$mikebd_bash_scripts_test_tmp_root/generated-extra-worktree"
(cd "$mikebd_bash_scripts_test_primary" && "$mikebd_bash_scripts_test_root/codex/launcher/new-worktree-launcher.sh" \
  --worktree-dir "$extra_target" \
  --branch feature/generated-extra \
  --from HEAD \
  --launcher "$extra_launcher" \
  --generator-marker "$marker" \
  --runner-relative-path scripts/dx/codex \
  --add-dir "$extra_add_dir_one" \
  --add-dir "$extra_add_dir_two" \
  --add-dir "$extra_add_dir_one") >"$mikebd_bash_scripts_test_tmp_root/new-extra-output"
mikebd_bash_scripts_test_assert_file_contains "$extra_launcher" "# codex-launcher-extra-add-dir-hex:"
CODEX_BIN="$mikebd_bash_scripts_test_fake" MIKEBD_BASH_SCRIPTS_TEST_FAKE_OUTPUT="$mikebd_bash_scripts_test_fake_output" CODEX_HOME="$mikebd_bash_scripts_test_tmp_root/generated-extra-codex-home" \
  CODEX_LAUNCHER_CONFIG="$mikebd_bash_scripts_test_config" "$extra_launcher" -- generated-extra
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_fake_output" "<$extra_add_dir_one>"
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_fake_output" "<$extra_add_dir_two>"

"$mikebd_bash_scripts_test_root/codex/launcher/session.sh" --generator-marker "$marker" --runner-relative-path scripts/dx/codex \
  pin --launcher "$launcher" --session-id session-123
mikebd_bash_scripts_test_assert_file_contains "$launcher" "default_session_id=session-123"

fork_launcher="$mikebd_bash_scripts_test_tmp_root/codex-fork"
CODEX_BIN="$mikebd_bash_scripts_test_fake" MIKEBD_BASH_SCRIPTS_TEST_FAKE_OUTPUT="$mikebd_bash_scripts_test_fake_output" CODEX_HOME="$mikebd_bash_scripts_test_tmp_root/generated-codex-home" \
  CODEX_LAUNCHER_CONFIG="$mikebd_bash_scripts_test_config" "$mikebd_bash_scripts_test_root/codex/launcher/session.sh" \
  --generator-marker "$marker" --runner-relative-path scripts/dx/codex \
  fork --launcher "$launcher" --target-launcher "$fork_launcher"
mikebd_bash_scripts_test_assert_file_contains "$fork_launcher" "default_session_id=child-123"

"$mikebd_bash_scripts_test_root/codex/launcher/session.sh" --generator-marker "$marker" --runner-relative-path scripts/dx/codex \
  pin --launcher "$extra_launcher" --session-id session-123
fork_add_dir="$mikebd_bash_scripts_test_tmp_root/fork-add-dir"
mkdir -p "$fork_add_dir"
fork_add_dirs_launcher="$mikebd_bash_scripts_test_tmp_root/codex-fork-add-dirs"
fork_add_dirs_codex_home="$mikebd_bash_scripts_test_tmp_root/fork-add-dirs-codex-home"
CODEX_BIN="$mikebd_bash_scripts_test_fake" MIKEBD_BASH_SCRIPTS_TEST_FAKE_OUTPUT="$mikebd_bash_scripts_test_fake_output" CODEX_HOME="$fork_add_dirs_codex_home" \
  CODEX_LAUNCHER_CONFIG="$mikebd_bash_scripts_test_config" "$mikebd_bash_scripts_test_root/codex/launcher/session.sh" \
  --generator-marker "$marker" --runner-relative-path scripts/dx/codex \
  fork --launcher "$extra_launcher" --target-launcher "$fork_add_dirs_launcher" --add-dir "$fork_add_dir" --add-dir "$fork_add_dir" --add-dir "$extra_add_dir_one"
fork_add_dirs_stored="$(mikebd_launcher_extra_add_dirs "$fork_add_dirs_launcher")"
[ "$(printf '%s\n' "$fork_add_dirs_stored" | grep -Fxc -- "$extra_add_dir_one")" -eq 1 ] || mikebd_bash_scripts_test_fail "forked launcher retained a duplicate inherited directory"
[ "$(printf '%s\n' "$fork_add_dirs_stored" | grep -Fxc -- "$extra_add_dir_two")" -eq 1 ] || mikebd_bash_scripts_test_fail "forked launcher did not retain its second inherited directory"
[ "$(printf '%s\n' "$fork_add_dirs_stored" | grep -Fxc -- "$fork_add_dir")" -eq 1 ] || mikebd_bash_scripts_test_fail "forked launcher retained a duplicate supplied directory"
CODEX_BIN="$mikebd_bash_scripts_test_fake" MIKEBD_BASH_SCRIPTS_TEST_FAKE_OUTPUT="$mikebd_bash_scripts_test_fake_output" CODEX_HOME="$fork_add_dirs_codex_home" \
  CODEX_LAUNCHER_CONFIG="$mikebd_bash_scripts_test_config" "$fork_add_dirs_launcher" -- fork-add-dirs
fork_add_dirs_args="$(grep -F 'ARGS:' "$mikebd_bash_scripts_test_fake_output")"
case "$fork_add_dirs_args" in
  *"<$extra_add_dir_one>"*"<$extra_add_dir_two>"*"<$fork_add_dir>"*) ;;
  *) mikebd_bash_scripts_test_fail "forked launcher did not preserve then append local directories" ;;
esac
adopt_codex_home="$mikebd_bash_scripts_test_tmp_root/adopt-codex-home"
mkdir -p "$adopt_codex_home/sessions/2026/01/01"
printf '{"type":"session_meta","payload":{"id":"adopted-123","forked_from_id":"different-parent","cwd":"%s"}}\n' "$extra_target" >"$adopt_codex_home/sessions/2026/01/01/adopted.jsonl"
adopted_launcher="$mikebd_bash_scripts_test_tmp_root/codex-adopted"
adopted_add_dir="$mikebd_bash_scripts_test_tmp_root/adopted-add-dir"
mkdir -p "$adopted_add_dir"
CODEX_HOME="$adopt_codex_home" CODEX_LAUNCHER_CONFIG="$mikebd_bash_scripts_test_config" \
  "$mikebd_bash_scripts_test_root/codex/launcher/session.sh" \
  --generator-marker "$marker" --runner-relative-path scripts/dx/codex \
  adopt --launcher "$extra_launcher" --target-launcher "$adopted_launcher" --session-id adopted-123 --add-dir "$adopted_add_dir" --add-dir "$adopted_add_dir" --add-dir "$extra_add_dir_two" \
  >"$mikebd_bash_scripts_test_tmp_root/adopt-output" 2>&1
adopted_stored="$(mikebd_launcher_extra_add_dirs "$adopted_launcher")"
[ "$(printf '%s\n' "$adopted_stored" | grep -Fxc -- "$extra_add_dir_one")" -eq 1 ] || mikebd_bash_scripts_test_fail "adopted launcher retained a duplicate inherited directory"
[ "$(printf '%s\n' "$adopted_stored" | grep -Fxc -- "$extra_add_dir_two")" -eq 1 ] || mikebd_bash_scripts_test_fail "adopted launcher retained a duplicate supplied directory"
[ "$(printf '%s\n' "$adopted_stored" | grep -Fxc -- "$adopted_add_dir")" -eq 1 ] || mikebd_bash_scripts_test_fail "adopted launcher retained a duplicate supplied directory"
mikebd_bash_scripts_test_assert_file_contains "$adopted_launcher" "default_session_id=adopted-123"
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_tmp_root/adopt-output" "info: adopted session adopted-123 forked from different-parent, not source launcher session session-123"
CODEX_BIN="$mikebd_bash_scripts_test_fake" MIKEBD_BASH_SCRIPTS_TEST_FAKE_OUTPUT="$mikebd_bash_scripts_test_fake_output" CODEX_HOME="$adopt_codex_home" \
  CODEX_LAUNCHER_CONFIG="$mikebd_bash_scripts_test_config" "$adopted_launcher" -- adopted
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_fake_output" "<$extra_add_dir_one>"
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_fake_output" "<$extra_add_dir_two>"
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_fake_output" "<$adopted_add_dir>"
adopted_args="$(grep -F 'ARGS:' "$mikebd_bash_scripts_test_fake_output")"
case "$adopted_args" in
  *"<$extra_add_dir_one>"*"<$extra_add_dir_two>"*"<$adopted_add_dir>"*) ;;
  *) mikebd_bash_scripts_test_fail "adopted launcher did not preserve then append local directories" ;;
esac
printf '{"type":"session_meta","payload":{"id":"wrong-worktree","cwd":"%s"}}\n' "$mikebd_bash_scripts_test_target" >"$adopt_codex_home/sessions/2026/01/01/wrong-worktree.jsonl"
wrong_worktree_launcher="$mikebd_bash_scripts_test_tmp_root/codex-wrong-worktree"
if CODEX_HOME="$adopt_codex_home" CODEX_LAUNCHER_CONFIG="$mikebd_bash_scripts_test_config" \
  "$mikebd_bash_scripts_test_root/codex/launcher/session.sh" \
  --generator-marker "$marker" --runner-relative-path scripts/dx/codex \
  adopt --launcher "$extra_launcher" --target-launcher "$wrong_worktree_launcher" --session-id wrong-worktree \
  >"$mikebd_bash_scripts_test_tmp_root/wrong-worktree-output" 2>&1; then
  mikebd_bash_scripts_test_fail "adopt accepted a session from another worktree"
fi
[ ! -e "$wrong_worktree_launcher" ] || mikebd_bash_scripts_test_fail "adopt created a launcher for another worktree"
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_tmp_root/wrong-worktree-output" "error: session wrong-worktree belongs to $mikebd_bash_scripts_test_target, not launcher worktree $extra_target"

legacy_launcher="$mikebd_bash_scripts_test_tmp_root/codex-legacy"
rm -rf "$mikebd_bash_scripts_test_tmp_root/generated-codex-home/sessions"
cat >"$legacy_launcher" <<EOF
#!/usr/bin/env bash
set -euo pipefail
$marker
worktree_dir=$mikebd_bash_scripts_test_target
default_session_id=session-123
EOF
chmod 700 "$legacy_launcher"
legacy_fork_launcher="$mikebd_bash_scripts_test_tmp_root/codex-legacy-fork"
CODEX_BIN="$mikebd_bash_scripts_test_fake" MIKEBD_BASH_SCRIPTS_TEST_FAKE_OUTPUT="$mikebd_bash_scripts_test_fake_output" CODEX_HOME="$mikebd_bash_scripts_test_tmp_root/generated-codex-home" \
  CODEX_LAUNCHER_CONFIG="$mikebd_bash_scripts_test_config" "$mikebd_bash_scripts_test_root/codex/launcher/session.sh" \
  --generator-marker "$marker" --runner-relative-path scripts/dx/codex \
  fork --launcher "$legacy_launcher" --target-launcher "$legacy_fork_launcher"
mikebd_bash_scripts_test_assert_file_contains "$legacy_fork_launcher" "default_session_id=child-123"

failing_prepare="$mikebd_bash_scripts_test_tmp_root/failing-prepare"
cat >"$failing_prepare" <<'EOF'
#!/usr/bin/env bash
exit 23
EOF
chmod 755 "$failing_prepare"
failed_target="$mikebd_bash_scripts_test_tmp_root/failed-prepare-worktree"
if (cd "$mikebd_bash_scripts_test_primary" && "$mikebd_bash_scripts_test_root/codex/launcher/new-worktree-launcher.sh" \
  --worktree-dir "$failed_target" \
  --branch feature/prepare-failure \
  --launcher "$mikebd_bash_scripts_test_tmp_root/codex-failed-prepare" \
  --prepare "$failing_prepare" \
  --generator-marker "$marker" \
  --runner-relative-path scripts/dx/codex) >"$mikebd_bash_scripts_test_tmp_root/failed-prepare-output" 2>&1; then
  mikebd_bash_scripts_test_fail "new-worktree launcher succeeded after preparation failed"
fi
[ ! -e "$failed_target" ] || mikebd_bash_scripts_test_fail "failed preparation left a worktree behind"
if git -C "$mikebd_bash_scripts_test_primary" show-ref --verify --quiet refs/heads/feature/prepare-failure; then
  mikebd_bash_scripts_test_fail "failed preparation left a branch behind"
fi

render_failure_launcher="$mikebd_bash_scripts_test_tmp_root/codex-render-failure"
render_failure_prepare="$mikebd_bash_scripts_test_tmp_root/render-failure-prepare"
cat >"$render_failure_prepare" <<'EOF'
#!/usr/bin/env bash
touch "$PREPARE_FAILURE_LAUNCHER"
EOF
chmod 755 "$render_failure_prepare"
render_failure_target="$mikebd_bash_scripts_test_tmp_root/failed-render-worktree"
if (cd "$mikebd_bash_scripts_test_primary" && PREPARE_FAILURE_LAUNCHER="$render_failure_launcher" "$mikebd_bash_scripts_test_root/codex/launcher/new-worktree-launcher.sh" \
  --worktree-dir "$render_failure_target" \
  --branch feature/render-failure \
  --launcher "$render_failure_launcher" \
  --prepare "$render_failure_prepare" \
  --generator-marker "$marker" \
  --runner-relative-path scripts/dx/codex) >"$mikebd_bash_scripts_test_tmp_root/failed-render-output" 2>&1; then
  mikebd_bash_scripts_test_fail "new-worktree launcher succeeded after rendering failed"
fi
[ ! -e "$render_failure_target" ] || mikebd_bash_scripts_test_fail "failed rendering left a worktree behind"
if git -C "$mikebd_bash_scripts_test_primary" show-ref --verify --quiet refs/heads/feature/render-failure; then
  mikebd_bash_scripts_test_fail "failed rendering left a branch behind"
fi
[ -e "$render_failure_launcher" ] || mikebd_bash_scripts_test_fail "rollback removed the externally created launcher"

stack_source="$mikebd_bash_scripts_test_target"
stack_source_branch="feature/test"
stack_source_name="$(basename "$stack_source")"
stack_suffix="-child"
stack_target="$(dirname "$stack_source")/${stack_source_name}${stack_suffix}"
stack_branch="${stack_source_branch}${stack_suffix}"
stack_home="$mikebd_bash_scripts_test_tmp_root/stack-home"
stack_launcher="$stack_home/.local/bin/codex-${stack_source_name}${stack_suffix}"
stack_add_dir_one="$mikebd_bash_scripts_test_tmp_root/stack-add-dir-one"
stack_add_dir_two="$mikebd_bash_scripts_test_tmp_root/stack-add-dir-two"
mkdir -p "$stack_add_dir_one" "$stack_add_dir_two"
printf 'uncommitted source change\n' >>"$stack_source/README.md"
(cd "$stack_source" && HOME="$stack_home" "$mikebd_bash_scripts_test_root/codex/launcher/stack-worktree-launcher.sh" \
  --suffix "$stack_suffix" \
  --generator-marker "$marker" \
  --runner-relative-path scripts/dx/codex \
  --add-dir "$stack_add_dir_one" \
  --add-dir "$stack_add_dir_two") >"$mikebd_bash_scripts_test_tmp_root/stack-output"
[ -d "$stack_target" ] || mikebd_bash_scripts_test_fail "stack launcher did not create a sibling worktree"
[ "$(git -C "$stack_target" branch --show-current)" = "$stack_branch" ] || \
  mikebd_bash_scripts_test_fail "stack launcher derived the wrong branch"
[ "$(git -C "$stack_target" rev-parse HEAD)" = "$(git -C "$stack_source" rev-parse HEAD)" ] || \
  mikebd_bash_scripts_test_fail "stack launcher did not use the source committed HEAD"
if grep -Fq 'uncommitted source change' "$stack_target/README.md"; then
  mikebd_bash_scripts_test_fail "stack launcher copied uncommitted source changes"
fi
mikebd_bash_scripts_test_assert_file_contains "$stack_launcher" "default_session_id=''"
stack_add_dirs="$(mikebd_launcher_extra_add_dirs "$stack_launcher")"
[ "$(printf '%s\n' "$stack_add_dirs" | grep -Fxc -- "$stack_add_dir_one")" -eq 1 ] || \
  mikebd_bash_scripts_test_fail "stack launcher omitted the first add-dir"
[ "$(printf '%s\n' "$stack_add_dirs" | grep -Fxc -- "$stack_add_dir_two")" -eq 1 ] || \
  mikebd_bash_scripts_test_fail "stack launcher omitted the second add-dir"

empty_runner_suffix="-empty-runner"
if (cd "$stack_source" && HOME="$stack_home" "$mikebd_bash_scripts_test_root/codex/launcher/stack-worktree-launcher.sh" \
  --suffix "$empty_runner_suffix" \
  --generator-marker "$marker" \
  --runner-relative-path "") >"$mikebd_bash_scripts_test_tmp_root/empty-runner-output" 2>&1; then
  mikebd_bash_scripts_test_fail "stack launcher accepted an empty runner path"
fi
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_tmp_root/empty-runner-output" "error: --runner-relative-path is required"
[ ! -e "$(dirname "$stack_source")/${stack_source_name}${empty_runner_suffix}" ] || \
  mikebd_bash_scripts_test_fail "empty runner path created a target worktree"
if git -C "$stack_source" show-ref --verify --quiet "refs/heads/${stack_source_branch}${empty_runner_suffix}"; then
  mikebd_bash_scripts_test_fail "empty runner path created a target branch"
fi

if (cd "$stack_source" && HOME="$stack_home" "$mikebd_bash_scripts_test_root/codex/launcher/stack-worktree-launcher.sh" \
  --suffix /unsafe \
  --generator-marker "$marker" \
  --runner-relative-path scripts/dx/codex) >"$mikebd_bash_scripts_test_tmp_root/unsafe-stack-output" 2>&1; then
  mikebd_bash_scripts_test_fail "stack launcher accepted an unsafe suffix"
fi
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_tmp_root/unsafe-stack-output" "error: suffix must be a single path-name fragment: /unsafe"

branch_collision_suffix="-branch-collision"
branch_collision="${stack_source_branch}${branch_collision_suffix}"
git -C "$stack_source" branch "$branch_collision"
if (cd "$stack_source" && HOME="$stack_home" "$mikebd_bash_scripts_test_root/codex/launcher/stack-worktree-launcher.sh" \
  --suffix "$branch_collision_suffix" \
  --generator-marker "$marker" \
  --runner-relative-path scripts/dx/codex) >"$mikebd_bash_scripts_test_tmp_root/branch-collision-output" 2>&1; then
  mikebd_bash_scripts_test_fail "stack launcher accepted an existing branch"
fi
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_tmp_root/branch-collision-output" "error: target branch already exists: $branch_collision"

launcher_collision_suffix="-launcher-collision"
launcher_collision_name="${stack_source_name}${launcher_collision_suffix}"
launcher_collision="$stack_home/.local/bin/codex-$launcher_collision_name"
mkdir -p "$(dirname "$launcher_collision")"
ln -s "$mikebd_bash_scripts_test_tmp_root/missing-launcher" "$launcher_collision"
if (cd "$stack_source" && HOME="$stack_home" "$mikebd_bash_scripts_test_root/codex/launcher/stack-worktree-launcher.sh" \
  --suffix "$launcher_collision_suffix" \
  --generator-marker "$marker" \
  --runner-relative-path scripts/dx/codex) >"$mikebd_bash_scripts_test_tmp_root/launcher-collision-output" 2>&1; then
  mikebd_bash_scripts_test_fail "stack launcher replaced an existing launcher"
fi
[ ! -e "$(dirname "$stack_source")/$launcher_collision_name" ] || \
  mikebd_bash_scripts_test_fail "launcher collision created a worktree"
[ -L "$launcher_collision" ] || \
  mikebd_bash_scripts_test_fail "launcher collision replaced the existing launcher"

git -C "$stack_source" switch --detach -q
if (cd "$stack_source" && HOME="$stack_home" "$mikebd_bash_scripts_test_root/codex/launcher/stack-worktree-launcher.sh" \
  --suffix -detached \
  --generator-marker "$marker" \
  --runner-relative-path scripts/dx/codex) >"$mikebd_bash_scripts_test_tmp_root/detached-stack-output" 2>&1; then
  mikebd_bash_scripts_test_fail "stack launcher accepted a detached source worktree"
fi
mikebd_bash_scripts_test_assert_file_contains "$mikebd_bash_scripts_test_tmp_root/detached-stack-output" "error: stack creation requires an attached source branch"
git -C "$stack_source" switch -q "$stack_source_branch"

echo "PASS: generic launcher tests"
