#!/usr/bin/env bash

set -euo pipefail

mikebd_bash_scripts_test_root=""
mikebd_bash_scripts_test_target=""
mikebd_bash_scripts_test_tmp_root=""
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
# shellcheck source=test-lib.sh disable=SC1091
source "$script_dir/test-lib.sh"
trap 'mikebd_bash_scripts_test_cleanup' EXIT

for portable_script in \
  "$mikebd_bash_scripts_test_root/git/worktree-links.sh" \
  "$mikebd_bash_scripts_test_root/codex/launcher/requirements.sh" \
  "$mikebd_bash_scripts_test_root/codex/launcher/launcher-lib.sh" \
  "$mikebd_bash_scripts_test_root/codex/launcher/run.sh" \
  "$mikebd_bash_scripts_test_root/codex/launcher/new-worktree-launcher.sh" \
  "$mikebd_bash_scripts_test_root/codex/launcher/stack-worktree-launcher.sh" \
  "$mikebd_bash_scripts_test_root/codex/launcher/session.sh"; do
  if grep -E 'declare[[:space:]]+-A|mapfile|readarray' "$portable_script" >/dev/null; then
    mikebd_bash_scripts_test_fail "$(basename "$portable_script") contains a Bash-4-only construct"
  fi
  if grep -F '< <(' "$portable_script" >/dev/null; then
    mikebd_bash_scripts_test_fail "$(basename "$portable_script") contains process substitution"
  fi
done

mikebd_bash_scripts_test_setup_fixture
marker='# Generated by generic launcher test; do not edit by hand.'
launcher="$mikebd_bash_scripts_test_tmp_root/codex-portable"
mikebd_launcher_render "$launcher" "$mikebd_bash_scripts_test_target" "" scripts/dx/codex "$marker"

file_mode() {
  local file="$1"
  local mode

  if mode="$("$real_stat" -c '%a' "$file" 2>/dev/null)"; then
    printf '%s\n' "$mode"
    return 0
  fi
  "$real_stat" -f '%Lp' "$file"
}

fake_bin="$mikebd_bash_scripts_test_tmp_root/fake-bin"
mkdir -p "$fake_bin"
real_stat="$(command -v stat)"
cat >"$fake_bin/stat" <<'EOF'
#!/usr/bin/env bash
if [ "${1:-}" = "-c" ]; then
  exit 1
fi
if [ "${1:-}" = "-f" ] && [ "${2:-}" = "%Lp" ]; then
  if mode="$("$REAL_STAT" -c '%a' "$3" 2>/dev/null)"; then
    printf '%s\n' "$mode"
    exit 0
  fi
  exec "$REAL_STAT" -f '%Lp' "$3"
fi
exec "$REAL_STAT" "$@"
EOF
chmod 755 "$fake_bin/stat"

REAL_STAT="$real_stat" PATH="$fake_bin:$PATH" \
  mikebd_launcher_update_session "$launcher" session-123 "$marker"
mode="$(file_mode "$launcher")"
[ "$mode" = "700" ] || mikebd_bash_scripts_test_fail "launcher mode = $mode, want 700 after BSD stat fallback"

echo "PASS: portable shared-script tests"
