#!/usr/bin/env bash

# Sourceable launcher rendering, metadata, and configuration helpers.
# Portability contract: Bash 3.2 on macOS and common GNU/Linux environments.

mikebd_launcher_assert_generated() {
  local launcher="$1"
  local marker="$2"

  [ -f "$launcher" ] || { echo "error: launcher does not exist: $launcher" >&2; return 1; }
  grep -Fqx "$marker" "$launcher" || {
    echo "error: launcher is not generated by the expected workflow: $launcher" >&2
    return 1
  }
}

mikebd_launcher_hex_encode() {
  [ -n "$1" ] || return 0
  LC_ALL=C printf '%s' "$1" | od -An -tx1 -v | tr -d ' \n'
}

mikebd_launcher_hex_decode() {
  local encoded="$1"
  local byte

  case "$encoded" in
    *[!0-9A-Fa-f]* ) echo "error: invalid launcher metadata encoding" >&2; return 1 ;;
  esac
  [ $(( ${#encoded} % 2 )) -eq 0 ] || {
    echo "error: invalid launcher metadata encoding" >&2
    return 1
  }

  while [ -n "$encoded" ]; do
    byte="${encoded:0:2}"
    printf '%b' "\\x$byte"
    encoded="${encoded:2}"
  done
  printf '\n'
}

mikebd_launcher_field_optional() {
  local launcher="$1"
  local field="$2"
  local metadata_prefix encoded

  metadata_prefix="# codex-launcher-$field-hex:"
  if grep -Fq "$metadata_prefix" "$launcher"; then
    encoded="$(sed -n "s/^# codex-launcher-${field}-hex: //p" "$launcher" | head -n 1)"
    mikebd_launcher_hex_decode "$encoded"
    return $?
  fi

  if ! grep -q "^${field}=" "$launcher"; then
    return 1
  fi
  encoded="$(sed -n "s/^${field}=//p" "$launcher" | head -n 1)"
  case "$encoded" in
    "''") printf '\n' ;;
    *[!A-Za-z0-9_./:-]*)
      echo "error: legacy launcher has an unsupported $field value: $launcher" >&2
      return 2
      ;;
    *) printf '%s\n' "$encoded" ;;
  esac
}

mikebd_launcher_field() {
  local launcher="$1"
  local field="$2"

  mikebd_launcher_field_optional "$launcher" "$field" || {
    [ "$?" -eq 1 ] && echo "error: launcher is missing $field: $launcher" >&2
    return 1
  }
}

mikebd_launcher_extra_add_dirs() {
  local launcher="$1"
  local encoded

  while IFS= read -r encoded; do
    [ -n "$encoded" ] || continue
    mikebd_launcher_hex_decode "$encoded"
  done <<<"$(sed -n 's/^# codex-launcher-extra-add-dir-hex: //p' "$launcher")"
}

mikebd_launcher_file_mode() {
  local launcher="$1"
  local mode

  if mode="$(stat -c '%a' "$launcher" 2>/dev/null)"; then
    printf '%s\n' "$mode"
    return 0
  fi

  mode="$(stat -f '%Lp' "$launcher")" || {
    echo "error: unable to determine launcher mode: $launcher" >&2
    return 1
  }
  printf '%s\n' "$mode"
}

mikebd_launcher_validate_runner_relative_path() {
  local runner_relative_path="$1"

  case "$runner_relative_path" in
    ""|/*|*".."*)
      echo "error: runner relative path must stay within the repository" >&2
      return 1
      ;;
  esac
}

mikebd_launcher_validate_marker() {
  local marker="$1"

  case "$marker" in
    \#*) ;;
    *)
      echo "error: generator marker must be a single shell comment line" >&2
      return 1
      ;;
  esac
  case "$marker" in
    *$'\n'*|*$'\r'*)
      echo "error: generator marker must be a single shell comment line" >&2
      return 1
      ;;
  esac
}

mikebd_launcher_render() {
  local launcher="$1"
  local worktree_dir="$2"
  local session_id="$3"
  local runner_relative_path="$4"
  local marker="$5"
  shift 5
  local launcher_dir temp quoted_worktree quoted_session quoted_runner
  local worktree_hex session_hex runner_hex extra_add_dir quoted_extra_add_dir extra_add_dir_hex

  [ ! -e "$launcher" ] || { echo "error: launcher already exists: $launcher" >&2; return 1; }
  mikebd_launcher_validate_marker "$marker" || return 1
  mikebd_launcher_validate_runner_relative_path "$runner_relative_path" || return 1
  if [ "$#" -gt 0 ]; then
    for extra_add_dir in "$@"; do
      case "$extra_add_dir" in
        /*) ;;
        *) echo "error: launcher extra directory must be absolute: $extra_add_dir" >&2; return 1 ;;
      esac
    done
  fi
  case "$session_id" in
    ""|*[!A-Za-z0-9_-]*)
      [ -z "$session_id" ] || { echo "error: invalid session ID: $session_id" >&2; return 1; }
      ;;
  esac

  launcher_dir="$(dirname "$launcher")"
  mkdir -p "$launcher_dir"
  quoted_worktree="$(printf '%q' "$worktree_dir")"
  quoted_session="$(printf '%q' "$session_id")"
  quoted_runner="$(printf '%q' "$runner_relative_path")"
  worktree_hex="$(mikebd_launcher_hex_encode "$worktree_dir")"
  session_hex="$(mikebd_launcher_hex_encode "$session_id")"
  runner_hex="$(mikebd_launcher_hex_encode "$runner_relative_path")"
  temp="$(mktemp "$launcher_dir/.codex-launcher.XXXXXX")"
  if ! {
    {
      printf '%s\n' '#!/usr/bin/env bash'
      printf '%s\n' 'set -euo pipefail'
      printf '%s\n' "$marker"
      printf '%s\n' "# codex-launcher-worktree_dir-hex: $worktree_hex"
      printf '%s\n' "# codex-launcher-default_session_id-hex: $session_hex"
      printf '%s\n' "# codex-launcher-runner_relative_path-hex: $runner_hex"
      for extra_add_dir in "$@"; do
        extra_add_dir_hex="$(mikebd_launcher_hex_encode "$extra_add_dir")"
        printf '%s\n' "# codex-launcher-extra-add-dir-hex: $extra_add_dir_hex"
      done
      printf 'worktree_dir=%s\n' "$quoted_worktree"
      printf 'default_session_id=%s\n' "$quoted_session"
      printf 'runner_relative_path=%s\n' "$quoted_runner"
      cat <<'EOF'
repo_root="$(git -C "$worktree_dir" rev-parse --show-toplevel)"
runner="$repo_root/$runner_relative_path"
[ -x "$runner" ] || { echo "error: missing launcher runner: $runner" >&2; exit 1; }
runner_args=(--worktree-dir "$worktree_dir")
if [ -n "$default_session_id" ]; then runner_args+=(--session-id "$default_session_id"); fi
EOF
      for extra_add_dir in "$@"; do
        quoted_extra_add_dir="$(printf '%q' "$extra_add_dir")"
        printf 'runner_args+=(--add-dir %s)\n' "$quoted_extra_add_dir"
      done
      cat <<'EOF'
exec "$runner" "${runner_args[@]}" -- "$@"
EOF
    } >"$temp"
    chmod 700 "$temp"
    mv "$temp" "$launcher"
  }; then
    rm -f "$temp"
    return 1
  fi
}

mikebd_launcher_update_session() {
  local launcher="$1"
  local session_id="$2"
  local marker="$3"
  local launcher_dir temp mode session_hex

  mikebd_launcher_assert_generated "$launcher" "$marker"
  case "$session_id" in
    ""|*[!A-Za-z0-9_-]*) echo "error: invalid session ID: $session_id" >&2; return 1 ;;
  esac
  grep -q '^default_session_id=' "$launcher" || {
    echo "error: launcher is missing default_session_id: $launcher" >&2
    return 1
  }
  launcher_dir="$(dirname "$launcher")"
  mode="$(mikebd_launcher_file_mode "$launcher")"
  session_hex="$(mikebd_launcher_hex_encode "$session_id")"
  temp="$(mktemp "$launcher_dir/.codex-launcher.XXXXXX")"
  if ! {
    awk -v session_id="$session_id" -v session_hex="$session_hex" '
      /^default_session_id=/ {$0="default_session_id=" session_id}
      /^# codex-launcher-default_session_id-hex: / {$0="# codex-launcher-default_session_id-hex: " session_hex}
      {print}
    ' "$launcher" >"$temp"
    chmod "$mode" "$temp"
    mv "$temp" "$launcher"
  }; then
    rm -f "$temp"
    return 1
  fi
}

mikebd_launcher_load_config() {
  local config_path="${CODEX_LAUNCHER_CONFIG:-${XDG_CONFIG_HOME:-$HOME/.config}/codex/launcher.env}"

  # These namespaced globals are the caller-facing launcher configuration.
  # shellcheck disable=SC2034
  CODEX_LAUNCHER_ADD_DIRS=()
  # shellcheck disable=SC2034
  CODEX_LAUNCHER_MODEL=""
  # shellcheck disable=SC2034
  CODEX_LAUNCHER_REASONING_EFFORT=""
  # shellcheck disable=SC2034
  CODEX_LAUNCHER_SANDBOX="workspace-write"
  # shellcheck disable=SC2034
  CODEX_LAUNCHER_USE_RTK="1"
  if [ -f "$config_path" ]; then
    # This is an explicitly user-owned Bash-compatible configuration fragment.
    # shellcheck disable=SC1090
    source "$config_path"
  fi
}

mikebd_launcher_codex_home_from_config() {
  printf '%s\n' "${CODEX_HOME:-$HOME/.codex}"
}

mikebd_launcher_config_codex_home() {
  mikebd_launcher_load_config
  mikebd_launcher_codex_home_from_config
}
